version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      # don't build 386
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: tekumara
      name: homebrew-tap
      token: "{{ .Env.TAP_REPO_TOKEN }}"
    directory: Formula
    homepage: https://github.com/tekumara/gh-doctor
    description: Set up and rotate github ssh keys

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^ci:'
