# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      # don't build 386
      - amd64
      - arm64

archives:
  # gh cli expects binaries
  - format: binary
    # generate name compatible with gh cli
    name_template: >-
      {{ .Binary }}-{{ .Os }}-{{ .Arch }}

brews:
  - repository:
      owner: tekumara
      name: homebrew-tap
      token: "{{ .Env.TAP_REPO_TOKEN }}"
    directory: Formula
    homepage: https://github.com/tekumara/gh-doctor
    description: GitHub Doctor creates SSH keys and uploads them to your account

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^ci:'
