name: release
on:
  push:
    tags: ["*"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: fetch tap repo token
        id: tap-repo-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_retrieval_mode: id
          # for https://github.com/tekumara/homebrew-tap
          installation_retrieval_payload: 37032952
      - name: goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_REPO_TOKEN: ${{ steps.tap-repo-token.outputs.token }}
